format = '''
$directory$git_branch$git_status$git_commit$fill $all\[$hostname:$time\]
$username$character'''
add_newline = true

[time]
disabled = false
format = '[$time]($style)'
time_format = '%Y-%m-%d %H:%M:%S'

[fill]
symbol = 'ï½¥'
style = 'bold #20436e'

[directory]
truncate_to_repo = false
truncation_length = 6

[username]
format = '[$user]($style) '
disabled = false
show_always = true
style_user = 'bold blue'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold green)'
disabled = false

[git_branch]
symbol = 'î‚ '
style = 'bold green'
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = 'bold green'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[cmd_duration]
min_time = 5000
format = '[âŒ›$duration](bold yellow) '

[line_break]
disabled = true

[php]
format = '[ğŸ˜$version](147 bold) '

[python]
format = '[$symbol$version](style) '
symbol = 'ğŸ'

[erlang]
symbol = "â“” "

[nodejs]
format = '[$symbol$version](bold green) '
symbol = "[â¬¢](bold green) "

[pulumi]
symbol = "ğŸ§Š"

[typst]
symbol = "t "
